using ZenoTypingAcademy.Models;

namespace ZenoTypingAcademy.Services;

public static class LessonService
{
    public static List<Lesson> GetLessons() => new()
    {
        new("b01", "F & J Home Anchors", "Foundation", "Feel the raised F and J keys. Keep index fingers anchored and relax the other fingers.", "f j ff jj fj jf fjf jfj", 10, 96),
        new("b02", "Left Home: A S D F", "Foundation", "Build left-hand home-row control.", "asdf fdsa asdf sad fad dad", 12, 96),
        new("b03", "Right Home: J K L ;", "Foundation", "Build right-hand home-row control.", "jkl; ;lkj jkl; jak lad;", 12, 96),
        new("b04", "Home Row Balance", "Foundation", "Alternate both hands without looking down.", "asdf jkl; fj dk sl a; fall dad ask", 14, 96),
        new("b05", "Home Row Words I", "Foundation", "Use home-row letters in short words.", "sad lad fall flask ask all dad salad", 15, 96),
        new("b06", "Home Row Words II", "Foundation", "Keep rhythm steady and fingers near home position.", "ask a lad; a sad fall; flask salad", 16, 97),
        new("b07", "Home Row Accuracy", "Foundation", "Accuracy before speed.", "asdf jkl; asdf jkl; fall; ask; salad;", 16, 98),
        new("b08", "Home Row Rhythm", "Foundation", "Type evenly instead of bursting.", "fj dk sl a; fj dk sl a; as df jk l;", 18, 97),
        new("b09", "Home Row Sentences", "Foundation", "Apply home-row control to sentence-like patterns.", "a lad asks; a flask falls; dad asks all.", 18, 97),
        new("b10", "Foundation Review", "Foundation", "Review posture, anchors, spacing and home row.", "asdf jkl; fall flask salad; a lad asks dad.", 20, 97),

        new("t01", "Reach E & I", "Top Row", "Reach upward and return to home row.", "de ed ki ik die kid did like", 18, 96),
        new("t02", "Reach R & U", "Top Row", "Train index-finger upward reaches.", "fr rf ju uj fur rude jury", 18, 96),
        new("t03", "Reach W & O", "Top Row", "Train ring-finger upward reaches.", "sw ws lo ol slow low wood", 18, 96),
        new("t04", "Reach Q & P", "Top Row", "Train pinky reaches with relaxed hands.", "aq qa ;p p; aqua pop app", 18, 96),
        new("t05", "Reach T & Y", "Top Row", "Use index fingers for central top-row keys.", "ft tf jy yj try tidy stay", 20, 96),
        new("t06", "Top Row Words I", "Top Row", "Mix home and top-row letters.", "type write quiet power pretty daily", 20, 96),
        new("t07", "Top Row Words II", "Top Row", "Build common-word fluency.", "people reply quality water story read", 22, 97),
        new("t08", "Top Row Alternation", "Top Row", "Alternate hands across the keyboard.", "quiet power type story reply water", 22, 97),
        new("t09", "Top Row Sentences", "Top Row", "Use natural sentence rhythm.", "We type quietly. People write daily. Your story is ready.", 24, 97),
        new("t10", "Top Row Review", "Top Row", "Review all top-row reaches.", "qwerty uiop typewriter quality power reply", 25, 97),

        new("m01", "Reach C & M", "Bottom Row", "Reach downward and return to home row.", "dc cd jm mj calm came mad", 20, 96),
        new("m02", "Reach X & ,", "Bottom Row", "Train ring fingers downward.", "sx xs k, ,k mix, six, max", 20, 96),
        new("m03", "Reach Z & .", "Bottom Row", "Train pinky/ring reach and period.", "az za l. .l lazy. jazz. maze.", 20, 96),
        new("m04", "Reach V & N", "Bottom Row", "Train index-finger downward reaches.", "fv vf jn nj van never even", 22, 96),
        new("m05", "Reach B", "Bottom Row", "Use the appropriate index finger consistently for B.", "fb bf jb bj baby big blue", 22, 96),
        new("m06", "Bottom Row Words I", "Bottom Row", "Mix bottom and home rows.", "calm name value zinc maximum brave", 22, 97),
        new("m07", "Bottom Row Words II", "Bottom Row", "Build whole-keyboard word control.", "camera number example balance move", 24, 97),
        new("m08", "Full Alphabet I", "Bottom Row", "Use all alphabet keys.", "quick brown fox jumps over the lazy dog", 25, 97),
        new("m09", "Full Alphabet II", "Bottom Row", "Practice broad key coverage.", "bright minds practice every day with calm focus", 26, 97),
        new("m10", "Alphabet Review", "Bottom Row", "Review all letter reaches without looking down.", "Pack my box with five dozen quality typing drills.", 28, 97),

        new("p01", "Capital Letters", "Punctuation", "Use Shift with the opposite hand.", "Zeno Academy Pakistan Student Teacher Windows", 24, 96),
        new("p02", "Period & Comma", "Punctuation", "Use punctuation without breaking rhythm.", "Practice slowly, then increase speed. Accuracy comes first.", 25, 97),
        new("p03", "Question & Exclamation", "Punctuation", "Practice shifted punctuation.", "Are you ready? Yes! Keep typing!", 25, 96),
        new("p04", "Colon & Semicolon", "Punctuation", "Practice formal punctuation.", "Plan: type; review; improve; repeat.", 26, 96),
        new("p05", "Quotes & Apostrophes", "Punctuation", "Practice dialogue and contractions.", "Don't rush. 'Accuracy first,' the coach said.", 26, 96),
        new("p06", "Brackets & Parentheses", "Punctuation", "Practice paired symbols.", "Use (clear notes), [labels], and {groups} carefully.", 26, 96),
        new("p07", "Hyphen & Underscore", "Punctuation", "Practice technical separators.", "well-known file_name user-id project_code", 28, 96),
        new("p08", "Slash & Backslash", "Punctuation", "Practice paths and ratios.", "A/B C/D C:\\Users\\Student\\Documents", 28, 96),
        new("p09", "Punctuation Paragraph", "Punctuation", "Combine common punctuation in prose.", "Today, we practice: commas, periods, questions, and quotes. Ready? Begin!", 30, 97),
        new("p10", "Punctuation Review", "Punctuation", "Complete punctuation assessment.", "Email: student@example.com; Ref #25; Total: $48.50; Status: Ready!", 30, 97),

        new("n01", "Numbers 1–5", "Numbers & Symbols", "Use the number row without looking down.", "1 2 3 4 5 12 34 51 23 45", 25, 97),
        new("n02", "Numbers 6–0", "Numbers & Symbols", "Complete number-row reaches.", "6 7 8 9 0 67 89 60 78 90", 25, 97),
        new("n03", "Full Number Row", "Numbers & Symbols", "Build numeric rhythm.", "12345 67890 2026 1500 9842 7316", 28, 97),
        new("n04", "Currency", "Numbers & Symbols", "Practice monetary entries.", "$25.50 $1,250.00 PKR 4500 USD 99.95", 28, 97),
        new("n05", "Percent & Hash", "Numbers & Symbols", "Practice common shifted symbols.", "10% 25% 99% #1 #2026 #ZENO", 28, 96),
        new("n06", "At & Email", "Numbers & Symbols", "Practice email-address patterns.", "student@zeno.test teacher@academy.test user_25@example.test", 30, 96),
        new("n07", "Math Symbols", "Numbers & Symbols", "Practice plus, minus, equals and arithmetic text.", "25+17=42 90-35=55 8*7=56 144/12=12", 30, 97),
        new("n08", "Dates & Times", "Numbers & Symbols", "Practice practical date/time entry.", "08/09/2026 09:30 AM 17:45 2026-09-08", 32, 97),
        new("n09", "Phone & Reference", "Numbers & Symbols", "Practice structured numeric strings.", "+92 300 1234567 REF-2026-00482 INV-000145", 32, 97),
        new("n10", "Numbers Review", "Numbers & Symbols", "Mixed number and symbol assessment.", "Invoice #204: 12 items @ $8.50 = $102.00; discount 5%.", 32, 97),

        new("c01", "TH Pattern", "Common Patterns", "Build the common th combination.", "the that this there their think three", 30, 97),
        new("c02", "ING Pattern", "Common Patterns", "Build fluent ing endings.", "typing learning working reading writing training", 30, 97),
        new("c03", "TION Pattern", "Common Patterns", "Practice common tion endings.", "education information action attention solution", 32, 97),
        new("c04", "ER / RE", "Common Patterns", "Practice alternating common pairs.", "teacher better order reader return report", 32, 97),
        new("c05", "OU / EA", "Common Patterns", "Practice common vowel pairs.", "could sound about read learn team", 32, 97),
        new("c06", "Double Letters", "Common Patterns", "Control repeated keystrokes.", "letter better common success office address", 32, 97),
        new("c07", "WH / SH / CH", "Common Patterns", "Practice common consonant clusters.", "what when show share change choose", 34, 97),
        new("c08", "PRE / PRO", "Common Patterns", "Practice common prefixes.", "prepare preview progress program project professional", 34, 97),
        new("c09", "MENT / NESS", "Common Patterns", "Practice common suffixes.", "development improvement kindness readiness", 34, 97),
        new("c10", "Pattern Review", "Common Patterns", "Mix high-frequency letter combinations.", "The professional training program improves typing readiness and attention.", 35, 98),

        new("s01", "20 WPM Accuracy", "Speed Builder", "Stay relaxed at 20 WPM.", "Accuracy is the foundation of lasting typing speed.", 20, 98),
        new("s02", "25 WPM Rhythm", "Speed Builder", "Use a steady rhythm.", "Smooth keystrokes build confidence and reduce unnecessary errors.", 25, 98),
        new("s03", "30 WPM Control", "Speed Builder", "Reach 30 WPM without sacrificing accuracy.", "Daily focused practice turns correct movement into automatic skill.", 30, 98),
        new("s04", "35 WPM Flow", "Speed Builder", "Keep eyes on text and hands relaxed.", "Good typists read slightly ahead while their fingers follow smoothly.", 35, 97),
        new("s05", "40 WPM Builder", "Speed Builder", "Build employable everyday speed.", "Clear communication becomes easier when typing no longer interrupts thought.", 40, 97),
        new("s06", "45 WPM Builder", "Speed Builder", "Increase pace in controlled steps.", "Consistent practice is more valuable than a single unusually fast test.", 45, 97),
        new("s07", "50 WPM Milestone", "Speed Builder", "Hit the first major speed milestone.", "Professional habits combine posture, accuracy, rhythm and controlled speed.", 50, 97),
        new("s08", "55 WPM Builder", "Speed Builder", "Reduce hesitation on difficult words.", "Anticipate common patterns and let trained fingers complete familiar sequences.", 55, 97),
        new("s09", "60 WPM Professional", "Speed Builder", "Maintain professional pace.", "Fast typing remains useful only when the final document is accurate and readable.", 60, 97),
        new("s10", "70 WPM Challenge", "Speed Builder", "Push speed while preserving technique.", "A calm typist can increase speed without striking the keys with unnecessary force.", 70, 96),
        new("s11", "80 WPM Challenge", "Speed Builder", "Train advanced fluency.", "Advanced speed develops from thousands of correct repetitions performed with control.", 80, 96),
        new("s12", "90 WPM Elite", "Speed Builder", "Build elite rhythm.", "Read ahead, maintain cadence, and recover from errors without losing concentration.", 90, 96),
        new("s13", "100 WPM Master", "Speed Builder", "Attempt the master speed target.", "Precision at high speed demonstrates mature keyboard control and excellent visual tracking.", 100, 96),
        new("s14", "Accuracy Recovery", "Speed Builder", "Slow down after error bursts and rebuild accuracy.", "Correct clean typing first; speed returns naturally when control is restored.", 45, 99),
        new("s15", "Consistency Test", "Speed Builder", "Keep pace stable from start to finish.", "Maintain one sustainable rhythm throughout the complete passage without rushing the ending.", 55, 98),

        new("o01", "Professional Email", "Office & Business", "Practice concise workplace email.", "Dear Team, please review the attached report and send your feedback by 3:00 PM. Regards, Zeno Office.", 40, 98),
        new("o02", "Meeting Notes", "Office & Business", "Practice structured meeting notes.", "Meeting: 10:00 AM. Agenda: sales, inventory, support. Action: prepare the weekly summary.", 42, 98),
        new("o03", "Business Letter", "Office & Business", "Practice formal business writing.", "Thank you for your inquiry. We are pleased to provide the requested information for your review.", 42, 98),
        new("o04", "Invoice Entry", "Office & Business", "Practice invoice descriptions and amounts.", "INV-1048 | Keyboard | Qty 12 | Rate 45.50 | Tax 5% | Total 573.30", 40, 99),
        new("o05", "Purchase Order", "Office & Business", "Practice purchase-order data.", "PO-2026-081 | Supplier: Nova Traders | Quantity: 250 | Delivery: 15 Sep 2026", 42, 99),
        new("o06", "Customer Support", "Office & Business", "Practice support responses.", "Your request has been received. Our support team will review the issue and provide an update shortly.", 45, 98),
        new("o07", "Memo", "Office & Business", "Practice internal memo formatting text.", "MEMO: All staff should submit attendance corrections before the monthly payroll is finalized.", 45, 98),
        new("o08", "Inventory Record", "Office & Business", "Practice stock-entry text.", "Item A-204 | Opening 450 | Received 120 | Issued 95 | Closing 475", 42, 99),
        new("o09", "Banking Entry", "Office & Business", "Practice financial descriptions.", "Receipt #8804: Cash received PKR 125,000.00 against customer account and posted successfully.", 42, 99),
        new("o10", "Report Paragraph", "Office & Business", "Practice formal report prose.", "The monthly report shows improved productivity, lower error rates, and faster response times across the team.", 48, 98),
        new("o11", "Spreadsheet Style", "Office & Business", "Practice tabular data as text.", "Product | Units | Rate | Amount; Alpha | 25 | 12.50 | 312.50; Beta | 40 | 8.75 | 350.00", 45, 99),
        new("o12", "Office Mastery", "Office & Business", "Mixed office-document assessment.", "Please update invoice INV-2045, confirm the 2:30 PM meeting, and email the revised stock report to the manager.", 50, 98),

        new("a01", "Science Practice", "Academic", "Type clear scientific prose.", "Energy can change form while the total amount of energy in a closed system remains conserved.", 38, 98),
        new("a02", "Technology Practice", "Academic", "Practice modern technology vocabulary.", "Software systems combine interfaces, data, logic, security, testing and reliable deployment.", 40, 98),
        new("a03", "Geography Practice", "Academic", "Practice geographic vocabulary.", "Rivers, mountains, plains and coastlines influence settlement, transport, agriculture and climate.", 40, 98),
        new("a04", "History Practice", "Academic", "Practice dates and historical prose.", "Historical records help researchers compare events, causes, decisions and long-term consequences.", 40, 98),
        new("a05", "Mathematics Practice", "Academic", "Practice mathematical language.", "A percentage compares a value with one hundred, while a ratio compares two quantities directly.", 40, 98),
        new("a06", "Business Studies", "Academic", "Practice business vocabulary.", "Revenue, cost, profit, cash flow and inventory are important measures in business operations.", 42, 98),
        new("a07", "Computer Studies", "Academic", "Practice computing vocabulary.", "A computer processes input, executes instructions, stores data and produces useful output.", 42, 98),
        new("a08", "Research Notes", "Academic", "Practice evidence-focused prose.", "A strong research note records the source, key finding, evidence, limitation and next question.", 44, 98),
        new("a09", "Essay Flow", "Academic", "Practice longer connected sentences.", "Effective learning requires curiosity, repeated practice, useful feedback and enough time to reflect on mistakes.", 45, 98),
        new("a10", "Academic Review", "Academic", "Mixed academic vocabulary assessment.", "Students improve when they combine careful reading, accurate typing, clear reasoning and consistent revision.", 45, 98),

        new("d01", "HTML Tags", "Coding", "Practice HTML syntax.", "<main><h1>Zeno Academy</h1><p>Learn typing.</p></main>", 30, 98),
        new("d02", "CSS Rules", "Coding", "Practice CSS punctuation.", ".card { padding: 16px; border-radius: 12px; font-size: 18px; }", 30, 98),
        new("d03", "JavaScript", "Coding", "Practice JavaScript syntax.", "const score = 98; if (score >= 95) { console.log('Excellent'); }", 32, 98),
        new("d04", "C# Basics", "Coding", "Practice C# syntax.", "public int Add(int a, int b) { return a + b; }", 32, 98),
        new("d05", "Kotlin Basics", "Coding", "Practice Kotlin syntax.", "fun greet(name: String): String = \"Hello, $name\"", 32, 98),
        new("d06", "Python Basics", "Coding", "Practice Python syntax and indentation text.", "def total(a, b): return a + b", 34, 98),
        new("d07", "SQL Query", "Coding", "Practice SQL syntax.", "SELECT id, name FROM students WHERE accuracy >= 95 ORDER BY name;", 34, 98),
        new("d08", "JSON Data", "Coding", "Practice quotes, braces and colons.", "{\"name\":\"Zeno\",\"wpm\":60,\"accuracy\":98}", 34, 99),
        new("d09", "API Path", "Coding", "Practice URLs and parameters.", "GET /api/v1/results?student=25&limit=20", 36, 98),
        new("d10", "Git Commands", "Coding", "Practice common developer commands.", "git status; git add .; git commit -m \"Improve lesson library\"; git push", 36, 98),
        new("d11", "Error Message", "Coding", "Practice technical diagnostic text.", "Build failed: check the file path, package version, configuration and compiler output.", 38, 98),
        new("d12", "Coding Mastery", "Coding", "Mixed code-symbol assessment.", "if (user.IsActive && score >= 90) { SaveResult(user.Id, score); }", 40, 98),

        new("k01", "NumPad Home 4-5-6", "NumPad & Data Entry", "Anchor the right hand around 4, 5 and 6.", "456 654 445 556 665 456456", 0, 99),
        new("k02", "NumPad Low 1-2-3", "NumPad & Data Entry", "Reach downward and return to 4-5-6.", "123 321 112 223 331 123123", 0, 99),
        new("k03", "NumPad High 7-8-9", "NumPad & Data Entry", "Reach upward and return to 4-5-6.", "789 987 778 889 997 789789", 0, 99),
        new("k04", "NumPad Zero", "NumPad & Data Entry", "Practice thumb/zero entry.", "100 200 500 1000 2500 9000", 0, 99),
        new("k05", "Decimal Entry", "NumPad & Data Entry", "Practice monetary decimals.", "12.50 99.95 450.00 1250.75 8.25", 0, 99),
        new("k06", "Addition Entry", "NumPad & Data Entry", "Practice plus and Enter workflow.", "125+75 450+225 99+101 1250+750", 0, 99),
        new("k07", "Subtraction Entry", "NumPad & Data Entry", "Practice subtraction strings.", "900-125 450-75 1000-250 88-19", 0, 99),
        new("k08", "Multiplication Entry", "NumPad & Data Entry", "Practice multiplication strings.", "12*8 25*4 45*6 125*3 99*9", 0, 99),
        new("k09", "Division Entry", "NumPad & Data Entry", "Practice division strings.", "144/12 500/25 900/30 1250/10", 0, 99),
        new("k10", "Invoice Amounts", "NumPad & Data Entry", "Practice realistic amount entry.", "1250.00 875.50 45000.00 99.99 125000.75", 0, 99),
        new("k11", "Quantity & Rate", "NumPad & Data Entry", "Practice paired business numbers.", "12 45.50 25 99.95 100 8.75 250 12.00", 0, 99),
        new("k12", "Data Entry Accuracy", "NumPad & Data Entry", "Prioritize zero-error numeric entry.", "845210 390125 775042 118905 640278", 0, 100),
        new("k13", "Long Numeric Strings", "NumPad & Data Entry", "Build numeric endurance.", "9845120376 1200457893 7788990012 4561237890", 0, 99),
        new("k14", "Accounting Batch", "NumPad & Data Entry", "Practice a batch of ledger-like values.", "15000.00 2750.50 998.25 450000.00 125.75 8800.00", 0, 99),
        new("k15", "NumPad Master Test", "NumPad & Data Entry", "Complete high-accuracy numeric assessment.", "1250.75 88.90 45000.00 725.25 100000.00 49.99 8705.50", 0, 100),

        new("u01", "Urdu Orientation", "Urdu", "Begin with familiar Urdu words while learning the selected Urdu keyboard layout.", "پاکستان اردو تعلیم کتاب قلم", 15, 96),
        new("u02", "Urdu Short Words", "Urdu", "Practice short common words.", "آج اب ہم یہ وہ ایک دو تین", 16, 96),
        new("u03", "Urdu Learning Words", "Urdu", "Practice education vocabulary.", "طالب علم استاد سبق مشق رفتار درستگی", 18, 96),
        new("u04", "Urdu Technology", "Urdu", "Practice technology vocabulary.", "کمپیوٹر سافٹ ویئر موبائل انٹرنیٹ پروگرام", 18, 96),
        new("u05", "Urdu Office", "Urdu", "Practice office vocabulary.", "دفتر رپورٹ حساب رسید رقم تاریخ", 20, 97),
        new("u06", "Urdu Sentence I", "Urdu", "Practice a short complete sentence.", "ہم روزانہ درست ٹائپنگ کی مشق کرتے ہیں۔", 20, 97),
        new("u07", "Urdu Sentence II", "Urdu", "Build sentence rhythm.", "اچھی رفتار کے ساتھ درستگی بھی ضروری ہے۔", 22, 97),
        new("u08", "Urdu Sentence III", "Urdu", "Practice longer connected Urdu text.", "مسلسل مشق سے ہاتھوں کی حرکت بہتر اور ٹائپنگ زیادہ آسان ہو جاتی ہے۔", 22, 97),
        new("u09", "Urdu Numbers Context", "Urdu", "Mix Urdu prose with numeric information.", "آج 25 طلبہ نے 30 منٹ کی ٹائپنگ مشق مکمل کی۔", 24, 97),
        new("u10", "Urdu Formal Text", "Urdu", "Practice formal educational prose.", "تعلیم میں مستقل مزاجی، توجہ اور درست مشق کامیابی کے اہم اصول ہیں۔", 25, 98),
        new("u11", "Urdu Office Text", "Urdu", "Practice workplace-style Urdu.", "براہ کرم ماہانہ رپورٹ مکمل کر کے متعلقہ دفتر میں جمع کروائیں۔", 25, 98),
        new("u12", "Urdu Speed Builder", "Urdu", "Increase speed without losing readability.", "تیز ٹائپنگ کے لیے پہلے درست انگلیوں کی عادت اور پھر مسلسل رفتار پیدا کریں۔", 28, 97),
        new("u13", "Urdu Accuracy", "Urdu", "Aim for very high accuracy.", "درست ٹائپنگ اچھی رفتار سے زیادہ اہم ہے کیونکہ غلطی وقت ضائع کرتی ہے۔", 28, 99),
        new("u14", "Urdu Paragraph", "Urdu", "Practice a longer paragraph.", "ایک ماہر ٹائپسٹ کی کوشش ہوتی ہے کہ وہ کی بورڈ کو دیکھے بغیر صاف، درست اور مسلسل انداز میں لکھ سکے۔", 30, 98),
        new("u15", "Urdu Mastery", "Urdu", "Complete Urdu track assessment.", "زینو ٹائپنگ اکیڈمی میں روزانہ مشق کریں، اپنی رفتار اور درستگی دیکھیں اور کمزور حروف پر دوبارہ کام کریں۔", 32, 98),

        new("e01", "Clerical Test I", "Exam Prep", "Practice formal clerical prose.", "All applications must be checked carefully before the final record is submitted to the responsible officer.", 35, 98),
        new("e02", "Clerical Test II", "Exam Prep", "Practice accuracy under time pressure.", "Candidates should read each passage carefully and maintain consistent speed throughout the test period.", 40, 98),
        new("e03", "Data Entry Test", "Exam Prep", "Mix names, codes and values.", "A-1024 | Customer 18 | 45 units | 125.50 | Approved | 08-09-2026", 40, 99),
        new("e04", "Office Recruitment", "Exam Prep", "Practice common office-test language.", "The selected employee will maintain records, prepare correspondence and enter accurate information into the system.", 45, 98),
        new("e05", "Five Minute Pace", "Exam Prep", "Prepare for sustained timed tests.", "Maintain a comfortable pace. Do not chase one fast line at the cost of errors in the remaining passage.", 45, 98),
        new("e06", "Ten Minute Endurance", "Exam Prep", "Build sustained concentration.", "Professional typing requires concentration over time, especially when the source contains numbers, names and punctuation.", 50, 98),
        new("e07", "Backspace Discipline", "Exam Prep", "Practice controlled correction behavior.", "Correct only when the test rules permit it, and avoid repeated corrections that destroy typing rhythm.", 50, 98),
        new("e08", "Accuracy Qualification", "Exam Prep", "Target qualification-grade accuracy.", "A strong result combines sufficient net speed with an error rate low enough to meet the required standard.", 50, 99),
        new("e09", "Professional Passage", "Exam Prep", "Practice formal high-density prose.", "Efficient administration depends on accurate records, timely communication, careful verification and responsible handling of information.", 55, 98),
        new("e10", "Final Master Assessment", "Exam Prep", "Final mixed professional assessment.", "Zeno Typing Academy measures speed, accuracy, consistency and errors so learners can improve through focused, measurable practice.", 60, 98),
    };
}
